# =============================================================================
# Flutter Build Action
# =============================================================================
#
# Purpose: Builds Flutter web application with caching and retry logic
# Performance: Uses extensive caching for dependencies and build artifacts
# Output: Stores Flutter build artifacts for integration step
#
# =============================================================================

name: "Flutter Build"
description: "Builds Flutter web application with caching and retry mechanisms"

inputs:
  flutter_version:
    description: "Flutter version to use"
    default: "3.24.1"
    required: false
  flutter_chart_ref:
    description: "Flutter chart repository reference"
    default: "master"
    required: false
  web_renderer:
    description: "Flutter web renderer"
    default: "html"
    required: false
  github_token:
    description: "GitHub token for repository access"
    required: true

outputs:
  build_size:
    description: "Size of the Flutter build"
    value: ${{ steps.build_stats.outputs.build_size }}
  artifact_name:
    description: "Name of the uploaded artifact"
    value: "flutter-build"

runs:
  using: composite
  steps:
    - name: Checkout flutter-chart
      uses: actions/checkout@v4
      with:
        repository: "deriv-com/flutter-chart"
        path: flutter-chart
        ref: ${{ inputs.flutter_chart_ref }}
        token: ${{ inputs.github_token }}

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ inputs.flutter_version }}
        channel: "stable"
        cache: true

    - name: Debug current directory
      shell: bash
      run: |
        echo "::group::Debug Information"
        echo "Current working directory: $(pwd)"
        echo "Directory contents:"
        ls -la
        echo "Flutter chart directory:"
        ls -la flutter-chart/ || echo "Flutter chart directory not found"
        echo "Chart app directory:"
        ls -la chart_app/ || echo "Chart app directory not found"
        echo "::endgroup::"

    - name: Cache Flutter dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.pub-cache
          chart_app/.dart_tool
        key: flutter-deps-${{ inputs.flutter_version }}-${{ hashFiles('**/pubspec.lock') }}
        restore-keys: |
          flutter-deps-${{ inputs.flutter_version }}-
          flutter-deps-

    - name: Cache Flutter build
      uses: actions/cache@v3
      with:
        path: chart_app/build
        key: flutter-build-${{ hashFiles('chart_app/**/*.dart', 'chart_app/pubspec.yaml') }}
        restore-keys: flutter-build-

    - name: Build Flutter application with retry
      uses: nick-fields/retry@v3
      with:
        timeout_minutes: 10
        max_attempts: 3
        shell: bash
        command: |
          set -e
          cd chart_app

          echo "::group::Installing Flutter dependencies"
          flutter pub get
          echo "::endgroup::"

          echo "::group::Building Flutter web application"
          flutter build web --web-renderer ${{ inputs.web_renderer }} --release --verbose
          echo "::endgroup::"

          # Verify build output exists
          if [ ! -d "build/web" ]; then
            echo "::error::Flutter build failed - no build/web directory found"
            exit 1
          fi

    - name: Report Flutter build size
      id: build_stats
      shell: bash
      run: |
        FLUTTER_SIZE=$(du -sh chart_app/build/web | cut -f1)
        echo "::notice::Flutter build size: $FLUTTER_SIZE"
        echo "build_size=$FLUTTER_SIZE" >> $GITHUB_OUTPUT

    - name: Upload Flutter build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: flutter-build
        path: chart_app/build/web
        retention-days: 1
